/**
 * Example View DDL SQL
 *
 * @author 	Jorg Janke
 * @version	$Id: XX_View.sql,v 1.1.1.3 2005/02/19 01:26:47 marco Exp $
 */

--	Inspect data
SELECT C_INVOICE_ID,
  AD_CLIENT_ID,AD_ORG_ID, ISACTIVE, CREATED,CREATEDBY, UPDATED,UPDATEDBY,
  ISSOTRX, DOCUMENTNO, DOCSTATUS, DOCACTION, PROCESSED,
  SALESREP_ID, DATEINVOICED, DATEPRINTED, DATEACCT,
  C_BPARTNER_ID, C_BPARTNER_LOCATION_ID, AD_USER_ID,
  C_CURRENCY_ID,
  TOTALLINES, GRANDTOTAL,
  MULTIPLIER, MULTIPLIERAP, DOCBASETYPE
FROM C_INVOICE_V
/

--	The view
CREATE OR REPLACE VIEW XX_BPartner_Total
AS
SELECT AD_CLIENT_ID,AD_ORG_ID, 
  'Y' AS ISACTIVE, SysDate AS CREATED, 0 AS CREATEDBY, SysDate AS UPDATED, 0 AS UPDATEDBY,
  C_BPARTNER_ID, C_BPARTNER_LOCATION_ID, AD_USER_ID,
  C_CURRENCY_ID,
  SUM(C_Invoice_Open (C_Invoice_ID) * MultiplierAP) AS OpenAmount
FROM C_INVOICE_V
WHERE Processed='Y' 
  AND IsPaid='N' 
GROUP BY AD_CLIENT_ID,AD_ORG_ID, 
  C_BPARTNER_ID, C_BPARTNER_LOCATION_ID, AD_USER_ID,
  C_CURRENCY_ID
/
